In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import itertools as it

In [2]:
stock = pd.read_csv('data/DJIA_table.xz',index_col=0)
news = pd.read_csv('data/RedditNews.xz',index_col=0)

In [3]:
stock.head()

,Open,High,Low,Close,Volume,Adj Close
Date,,,,,,
2016-07-01,17924.240234,18002.380859,17916.910156,17949.369141,82160000,17949.369141
2016-06-30,17712.759766,17930.609375,17711.800781,17929.990234,133030000,17929.990234
2016-06-29,17456.019531,17704.509766,17456.019531,17694.679688,106380000,17694.679688
2016-06-28,17190.509766,17409.720703,17190.509766,17409.720703,112190000,17409.720703
2016-06-27,17355.210938,17355.210938,17063.080078,17140.240234,138740000,17140.240234

In [4]:
filter_out = news.groupby('Date').count().query('News != 25').index

In [5]:
news.drop(labels=filter_out,axis=0, inplace=True)

In [6]:
dates = news.index
prev = dates[0]
cnt = 0
cnts = []
for date in dates:
    if date == prev:
        cnt += 1
        cnts.append(cnt)
    else:
        cnt = 1
        cnts.append(cnt)
        prev = date

In [7]:
news['Rank'] = cnts

In [8]:
news.shape

(73275, 2)

In [9]:
news.drop_duplicates(inplace=True)

In [10]:
news.shape

(73274, 2)

In [13]:
news = news.pivot(columns='Rank',values='News')

In [14]:
news.head()

Rank,1,2,3,4,5,6,7,8,9,10,...,16,17,18,19,20,21,22,23,24,25
Date,,,,,,,,,,,,,,,,,,,,,
2008-06-08,b'Nim Chimpsky: The tragedy of the chimp who t...,"b""Canada: Beware slippery slope' to censorship...",b'EU Vice-President Luisa Morgantini and the I...,"b""Israeli minister: Israel will attack Iran if...",b'Albino Killings in Tanzania. At least 19 alb...,b'Chiapas: army occupies Zapatista communities...,"b'Polar bear swims 200 miles, is shot dead upo...","b'News is a contraband item in Pakistan now, a...","b'Albinos, Long Shunned, Face Threat in Tanzan...",b'Town in Britain Plans to Start its Own Curre...,...,"b""S. Korean protesters, police clash in beef r...","b""Oil reserves 'will last decades' - a BBC Sco...",b'Cameras designed to detect terrorist facial ...,b'Israeli peace activists protest 41 years of ...,"b""A 5.1 earthquake hits China's Southern Qingh...",b'Man goes berzerk in Akihabara and stabs ever...,b'Threat of world AIDS pandemic among heterose...,b'Angst in Ankara: Turkey Steers into a Danger...,"b""UK: Identity cards 'could be used to spy on ...","b'Marriage, they said, was reduced to the stat..."
2008-06-09,b'United States quits Human Rights Council',"b""Pentagon blocked Cheney's attack on Iran""","b""'J Street,' a new liberal Jewish organizatio...","b'Former Ambassador Joseph Wilson: ""[The U.S. ...",b'EU leaders anxiously await Irish verdict on ...,"b"" 17 Hit or Stabbed, 7 Confirmed Dead in Toky...",b'Treaty tensions mount as Iraq tells the US i...,"b""Council paints over street artist Banksy's g...","b'""Finders keepers"" can get complicated when h...","b'Chew Qat: In Yemen, 72 per cent of men and 3...",...,b'35 Ukraine miners trapped underground - thre...,b'Bilderberg attendee Geithner calls for globa...,"b'Jos Manuel Barroso bullies the Irish, saying...","b""Don't worry everyone, AIDS is officially over!""",b'What if Bush Attacks Iran on His Way Out of ...,b'Future of the United States of Europe in the...,"b""'Military coup' in Zimbabwe as Mugabe is for...",b'Rising Oil Prices Spark Strikes in Spain and...,"b'Chvez to FARC: Asks to end armed strugle, ""T...",b'Fliers in for pain as airlines pack it in'
2008-06-10,"b'Oil shortage a myth, says industry insider'","b""Israel launches 'Iran Command' for war""","b""Petition Calling for an Investigation into 9...",b'Canadian HRC Tribunal forces pastor to publi...,b'US and EU threaten to freeze Iranian assets ...,b'Thousands of UK homeowners face negative equ...,b'31 year old beats 3 year old to death: worst...,b'White House Saying Senate Doesn\'t Get to Vo...,b'Man escapes North Korea after 33 years',b'The 14-year-old Afghan suicide bomber',...,b'Shanghai Composite tumbles 7.7 percent ',b'Olmert Hints That U.S. Attack On Iran Is Near',b'Is Israel planning on using nukes in its nex...,b'USS Liberty -- New Revelations in Attack on ...,"b""World's first church unearthed in Jordan """,b'Corruption in Ukraine allows epidemic to rea...,b'Bush Discusses Iran Sanctions With EU Leaders',"b""Tibet and the Olympic `tradition'""",b'Saddam tribe leader murdered in Iraq',b'Law creates underclass of child criminals'
2008-06-11,b'BBC uncovers lost Iraq billions',b'War Criminal George W. Bush not Welcome in t...,"b'Offensive Speech: US says it\'s ""free"", othe...",b'Bush/Cheney Plan Demands 58 US Bases In Iraq...,b'Grocery refuses to sell Jack Daniels barbecu...,b'On farewell tour of Europe: Bush steps up th...,"b""Pakistan Blames U.S. Coalition for Troops' D...",b'Senior intelligence officer leaves top secre...,b'Food for schoolchildren was ordered to be gi...,"b""Cuba's City Gardens Flourish and 70% Of Vege...",...,b'Iran 1st in Middle East stem cell research',"b' Set a Guinness World Record, Enjoy a Better...","b'France blocks online child porn, terrorism, ...","b'""Race for Life"" coming to Czech Republic'","b""They're Killing Us Darling. They Really Are....",b'OPEC Supports Saudi-Backed Oil Summit',b'A major and twelve Pakistani soldiers martyred',b'Turkish PM: court must explain headscarf rul...,b'crazy fitness tools from 1860 ',b'2 US Lawmakers say computers compromised by ...
2008-06-12,"b'Did US attack Pakistan last night? ""Pakistan...","b'If U.S. or Israel drops a bomb on Iran, it w...","b""Top Secret documents on Al-Qaeda left on a t...",b'Seoul protest that started over allowing pos...,"b""'Jewish settler attack' on film """,b'Cult of Scientology has disabled man from Pl...,b'No one knows the long-term carrying capacity...,b'Robert Mugabe is stealing food aid from the ...,"b'Huh, the American establishment has a LONG h...","b'Marine ""Mean Motari"" gets expelled, another ...",...,"b'Chinese are naming children ""Olympic Games""'",b'Pentagon released video of a controversial a...,"b'4 dead, 40 hurt as tornado hits Boy Scout camp'","b""Islamic Cleric Issues Fatwa Condemning Gambi...",b'Footage of deadly US airstrike',"b'British MP to resign, seek-relection in defe...","b""John McCain believes that it would be a good...",b'China &amp; Taiwan reopen talks',b'Estonian parliament approves EU Lisbon Treat...,b'Ukranian Women Strip in Protest'

In [15]:
news.shape

(2931, 25)

In [16]:
combo = pd.read_csv('data/Combined_News_DJIA.xz')

In [18]:
combo.shape

(1989, 27)

In [20]:
stock.shape

(1989, 6)